### ISSUE TITLE
Windows 11 Start index cannot be lessthan zero

### ISSUE THREAD

**Issue by ankitj1611** [UndertakerBen/PorChromeUpd#11]
Hi I have latest release of Portable Chrome Updater 1.4.2.0 which was working fine in Windows 10 22H2, today I updated to Windows 11 and it is giving me error after launching main app

- I have tried compatibility setting and set to previous version of windows
- Tried downloading fresh copy

Anyone else getting this in Windows 11 22H2??

<img width="518" alt="image" src="https://user-images.githubusercontent.com/20925775/206187738-b5e542b2-2979-4b93-b81a-0b62e2c35394.png">

**Comment by amuagarwal** [comment]
Even on windows 10, I doubt this error coming when updater trying to parse the version

**Comment by CanastraRF** [comment]
Same here on Windows 10 22H2 since some days.

**Comment by UndertakerBen** [comment]
This should be fixed with version 1.4.3.0.
https://github.com/UndertakerBen/PorChromeUpd/releases/tag/v1.4.3.0

**Comment by ankitj1611** [comment]
> This should be fixed with version 1.4.3.0. https://github.com/UndertakerBen/PorChromeUpd/releases/tag/v1.4.3.0

Hi thanks working perfect now

**Comment by Radder124** [comment]
The same problem happens again.
