### ISSUE TITLE
Portable Chrome Updater

### ISSUE THREAD

**Issue by BB69** [UndertakerBen/PorChromeUpd#3]
Hi again

Beta-Version update don't work since 2 days!

Thanks for the problem solution and also for fixing the brave update problem.

regards
Beat

[2021-06-24_120542.pdf](https://github.com/UndertakerBen/PorChromeUpd/files/6708341/2021-06-24_120542.pdf)

**Comment by UndertakerBen** [comment]
Thanks. 
This problem occurred with the portable **Edge** (Chromium) updater. I have fixed it in version [1.4.2.0](https://github.com/UndertakerBen/PorEdgeUpd/releases/tag/v1.4.2.0) for now by backporting the method to retrieve the version numbers.
